services:
  # geth-init:
  #   image: ethereum/client-go:latest
  #   volumes:
  #     - ./dex/data:/data/geth
  #     - ./dex/data:/gen
  #   command: init /gen/genesis.json
  
  geth:
    image: ethereum/client-go:latest
    ports:
      - "8547:8547"
      - "8546:8546"
    # volumes:
    #   - ./dex/data:/data/geth
    command: >
      --http
      --http.addr 0.0.0.0
      --http.port 8547
      --http.api eth,net,web3,personal,miner
      --http.corsdomain "*"
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --ws.api eth,net,web3,personal,miner
      --verbosity 3
      --datadir /data/geth
      --networkid 1337
      --dev

  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: sh -c "go run main.go"
    volumes:
      - .:/go-dex
    networks:
      - app_network
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  postgres:
    container_name: postgres
    image: postgres:16.2-alpine
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  go-dex:

networks:
  app_network: